# Generated by Django 2.2.1 on 2019-07-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('pid', models.ForeignKey(null=0, on_delete=django.db.models.deletion.CASCADE, to='items.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('price', models.FloatField()),
                ('available', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=None, to='items.Category')),
            ],
        ),
    ]
