# Generated by Django 2.2.1 on 2019-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pid',
            field=models.IntegerField(blank=True, null=1),
        ),
    ]
