# Generated by Django 2.2.1 on 2019-07-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190721_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Category'),
        ),
    ]
