# Generated by Django 2.2.1 on 2019-08-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20190813_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categories',
        ),
    ]
